# Generated by spacemacs2nix.el
p:
let checked = n:
  let
    n' = builtins.replaceStrings ["+"] ["-plus"] n;
    p' = p.${n'} or null;
  in if p'.meta.broken or false then null else p';
in
{
  "vim-powerline" = [
    (checked "powerline")
    (checked "vim-powerline")
  ];
  "evil-cleverparens" = [
    (checked "evil-cleverparens")
  ];
  "evil-snipe" = [
    (checked "evil-snipe")
    (checked "magit")
    (checked "ranger")
  ];
  "vim-empty-lines" = [
    (checked "vim-empty-lines-mode")
    (checked "vi-tilde-fringe")
  ];
  "evil-commentary" = [
    (checked "evil-commentary")
    (checked "evil-nerd-commenter")
  ];
  "vinegar" = [
    (checked "diff-hl")
    (checked "dired")
  ];
  "themes-megapack" = [
    (checked "afternoon-theme")
    (checked "alect-themes")
    (checked "ample-theme")
    (checked "ample-zen-theme")
    (checked "apropospriate-theme")
    (checked "anti-zenburn-theme")
    (checked "badwolf-theme")
    (checked "birds-of-paradise-plus-theme")
    (checked "bubbleberry-theme")
    (checked "busybee-theme")
    (checked "cherry-blossom-theme")
    (checked "clues-theme")
    (checked "color-theme-sanityinc-solarized")
    (checked "color-theme-sanityinc-tomorrow")
    (checked "cyberpunk-theme")
    (checked "dakrone-theme")
    (checked "darkburn-theme")
    (checked "darkmine-theme")
    (checked "darkokai-theme")
    (checked "darktooth-theme")
    (checked "django-theme")
    (checked "dracula-theme")
    (checked "espresso-theme")
    (checked "exotica-theme")
    (checked "farmhouse-theme")
    (checked "flatland-theme")
    (checked "flatui-theme")
    (checked "gandalf-theme")
    (checked "gotham-theme")
    (checked "grandshell-theme")
    (checked "gruber-darker-theme")
    (checked "gruvbox-theme")
    (checked "hc-zenburn-theme")
    (checked "hemisu-theme")
    (checked "heroku-theme")
    (checked "inkpot-theme")
    (checked "ir-black-theme")
    (checked "jazz-theme")
    (checked "jbeans-theme")
    (checked "light-soap-theme")
    (checked "lush-theme")
    (checked "madhat2r-theme")
    (checked "majapahit-theme")
    (checked "material-theme")
    (checked "minimal-theme")
    (checked "moe-theme")
    (checked "molokai-theme")
    (checked "monokai-theme")
    (checked "monochrome-theme")
    (checked "mustang-theme")
    (checked "naquadah-theme")
    (checked "noctilux-theme")
    (checked "obsidian-theme")
    (checked "occidental-theme")
    (checked "omtose-phellack-theme")
    (checked "oldlace-theme")
    (checked "organic-green-theme")
    (checked "phoenix-dark-mono-theme")
    (checked "phoenix-dark-pink-theme")
    (checked "planet-theme")
    (checked "professional-theme")
    (checked "purple-haze-theme")
    (checked "railscasts-theme")
    (checked "rebecca-theme")
    (checked "reverse-theme")
    (checked "seti-theme")
    (checked "smyx-theme")
    (checked "soft-charcoal-theme")
    (checked "soft-morning-theme")
    (checked "soft-stone-theme")
    (checked "solarized-theme")
    (checked "soothe-theme")
    (checked "spacegray-theme")
    (checked "subatomic-theme")
    (checked "subatomic256-theme")
    (checked "sublime-themes")
    (checked "sunny-day-theme")
    (checked "tango-2-theme")
    (checked "tango-plus-theme")
    (checked "tangotango-theme")
    (checked "tao-theme")
    (checked "toxi-theme")
    (checked "twilight-anti-bright-theme")
    (checked "twilight-bright-theme")
    (checked "twilight-theme")
    (checked "ujelly-theme")
    (checked "underwater-theme")
    (checked "white-sand-theme")
    (checked "zen-and-art-theme")
    (checked "zenburn-theme")
  ];
  "colors" = [
    (checked "nyan-mode")
    (checked "color-identifiers-mode")
    (checked "rainbow-identifiers")
    (checked "rainbow-mode")
  ];
  "theming" = [
    (checked "theming")
  ];
  "react" = [
    (checked "company")
    (checked "company-tern")
    (checked "emmet-mode")
    (checked "evil-matchit")
    (checked "flycheck")
    (checked "js-doc")
    (checked "smartparens")
    (checked "tern")
    (checked "web-beautify")
    (checked "web-mode")
  ];
  "ruby-on-rails" = [
    (checked "feature-mode")
    (checked "projectile-rails")
    (checked "which-key")
  ];
  "django" = [
    (checked "pony-mode")
  ];
  "git" = [
    (checked "evil-magit")
    (checked "fill-column-indicator")
    (checked "gitattributes-mode")
    (checked "gitconfig-mode")
    (checked "gitignore-mode")
    (checked "git-commit")
    (checked "git-link")
    (checked "git-messenger")
    (checked "git-timemachine")
    (checked "helm-gitignore")
    (checked "magit")
    (checked "magit-gitflow")
    (checked "orgit")
    (checked "smeargle")
  ];
  "perforce" = [
    (checked "p4")
  ];
  "version-control" = [
    (checked "diff-mode")
    (checked "diff-hl")
    (checked "evil-unimpaired")
    (checked "git-gutter")
    (checked "git-gutter+")
    (checked "git-gutter-fringe")
    (checked "git-gutter-fringe+")
    (checked "smerge-mode")
  ];
  "github" = [
    (checked "gist")
    (checked "github-browse-file")
    (checked "github-clone")
    (checked "github-search")
    (checked "magit-gh-pulls")
    (checked "spacemacs-github")
  ];
  "nixos" = [
    (checked "company")
    (checked "company-nixos-options")
    (checked "helm-nixos-options")
    (checked "nix-mode")
    (checked "nixos-options")
  ];
  "osx" = [
    (checked "exec-path-from-shell")
    (checked "helm")
    (checked "launchctl")
    (checked "osx-dictionary")
    (checked "osx-trash")
    (checked "pbcopy")
    (checked "reveal-in-osx-finder")
    (checked "term")
  ];
  "nlinum" = [
    (checked "linum")
    (checked "linum-relative")
    (checked "nlinum")
    (checked "nlinum-relative")
  ];
  "cscope" = [
    (checked "helm-cscope")
    (checked "xcscope")
  ];
  "gtags" = [
    (checked "ggtags")
    (checked "helm-gtags")
  ];
  "spacemacs-ui" = [
    (checked "ace-link")
    (checked "centered-cursor")
    (checked "desktop")
    (checked "doc-view")
    (checked "flx-ido")
    (checked "info+")
    (checked "open-junk-file")
    (checked "paradox")
    (checked "restart-emacs")
    (checked "winum")
  ];
  "spacemacs-evil" = [
    (checked "evil-anzu")
    (checked "evil-args")
    (checked "evil-ediff")
    (checked "evil-exchange")
    (checked "evil-iedit-state")
    (checked "evil-indent-plus")
    (checked "evil-lisp-state")
    (checked "evil-mc")
    (checked "evil-nerd-commenter")
    (checked "evil-matchit")
    (checked "evil-numbers")
    (checked "evil-search-highlight-persist")
    (checked "evil-surround")
    (checked "evil-tutor")
    (checked "evil-unimpaired")
    (checked "evil-visual-mark-mode")
    (checked "hs-minor-mode")
    (checked "linum-relative")
    (checked "vi-tilde-fringe")
  ];
  "spacemacs-misc" = [
    (checked "dumb-jump")
    (checked "request")
  ];
  "spacemacs-ui-visual" = [
    (checked "ansi-colors")
    (checked "fancy-battery")
    (checked "fill-column-indicator")
    (checked "golden-ratio")
    (checked "hl-todo")
    (checked "neotree")
    (checked "popup")
    (checked "popwin")
    (checked "smooth-scrolling")
    (checked "spaceline")
    (checked "zoom-frm")
  ];
  "spacemacs-completion" = [
    (checked "default-helm-config")
    (checked "default-ivy-config")
    (checked "ido")
    (checked "ido-vertical-mode")
  ];
  "spacemacs-layouts" = [
    (checked "eyebrowse")
    (checked "helm")
    (checked "ivy")
    (checked "persp-mode")
    (checked "spaceline")
    (checked "swiper")
  ];
  "spacemacs-editing-visual" = [
    (checked "adaptive-wrap")
    (checked "auto-highlight-symbol")
    (checked "column-enforce-mode")
    (checked "hide-comnt")
    (checked "highlight-indentation")
    (checked "highlight-numbers")
    (checked "highlight-parentheses")
    (checked "hl-anything")
    (checked "indent-guide")
    (checked "rainbow-delimiters")
    (checked "volatile-highlights")
  ];
  "spacemacs-editing" = [
    (checked "aggressive-indent")
    (checked "avy")
    (checked "bracketed-paste")
    (checked "clean-aindent-mode")
    (checked "eval-sexp-fu")
    (checked "expand-region")
    (checked "hexl")
    (checked "hungry-delete")
    (checked "link-hint")
    (checked "lorem-ipsum")
    (checked "move-text")
    (checked "origami")
    (checked "smartparens")
    (checked "spacemacs-whitespace-cleanup")
    (checked "undo-tree")
    (checked "uuidgen")
    (checked "ws-butler")
  ];
  "spacemacs-org" = [
    (checked "flyspell")
    (checked "default-org-config")
    (checked "org-plus-contrib")
    (checked "org-bullets")
    (checked "space-doc")
    (checked "toc-org")
  ];
  "spacemacs-language" = [
    (checked "define-word")
    (checked "google-translate")
  ];
  "emoji" = [
    (checked "emoji-cheat-sheet-plus")
    (checked "company-emoji")
  ];
  "selectric" = [
    (checked "selectric-mode")
  ];
  "xkcd" = [
    (checked "xkcd")
  ];
  "games" = [
    (checked "2048-game")
    (checked "helm-games")
    (checked "pacmacs")
    (checked "tetris")
    (checked "sudoku")
    (checked "typit")
  ];
  "floobits" = [
    (checked "floobits")
  ];
  "spacemacs-base" = [
    (checked "abbrev")
    (checked "ace-window")
    (checked "archive-mode")
    (checked "bookmark")
    (checked "centered-buffer-mode")
    (checked "conf-mode")
    (checked "dired")
    (checked "dired-x")
    (checked "electric-indent-mode")
    (checked "ediff")
    (checked "eldoc")
    (checked "evil-escape")
    (checked "evil-evilified-state")
    (checked "evil-visualstar")
    (checked "exec-path-from-shell")
    (checked "help-fns+")
    (checked "hi-lock")
    (checked "holy-mode")
    (checked "hybrid-mode")
    (checked "image-mode")
    (checked "imenu")
    (checked "linum")
    (checked "occur-mode")
    (checked "package-menu")
    (checked "page-break-lines")
    (checked "pcre2el")
    (checked "process-menu")
    (checked "projectile")
    (checked "recentf")
    (checked "savehist")
    (checked "saveplace")
    (checked "spacemacs-theme")
    (checked "subword")
    (checked "tar-mode")
    (checked "uniquify")
    (checked "url")
    (checked "visual-line-mode")
    (checked "whitespace")
    (checked "winner")
  ];
  "spacemacs" = [
  ];
  "spacemacs-bootstrap" = [
    (checked "async")
    (checked "bind-map")
    (checked "bind-key")
    (checked "diminish")
    (checked "evil")
    (checked "hydra")
    (checked "use-package")
    (checked "which-key")
  ];
  "spotify" = [
    (checked "spotify")
    (checked "helm-spotify-plus")
  ];
  "wakatime" = [
    (checked "wakatime-mode")
  ];
  "search-engine" = [
    (checked "engine-mode")
  ];
  "elfeed" = [
    (checked "elfeed")
    (checked "elfeed-goodies")
    (checked "elfeed-org")
    (checked "elfeed-web")
  ];
  "twitter" = [
    (checked "twittering-mode")
  ];
  "evernote" = [
    (checked "geeknote")
  ];
  "org" = [
    (checked "company")
    (checked "company-emoji")
    (checked "emoji-cheat-sheet-plus")
    (checked "evil-org")
    (checked "evil-surround")
    (checked "gnuplot")
    (checked "htmlize")
    (checked "mu4e")
    (checked "ob")
    (checked "org")
    (checked "org-agenda")
    (checked "org-download")
    (checked "org-mime")
    (checked "org-pomodoro")
    (checked "org-present")
    (checked "org-projectile")
    (checked "ox-twbs")
    (checked "ox-gfm")
    (checked "ox-reveal")
    (checked "persp-mode")
  ];
  "ibuffer" = [
    (checked "ibuffer")
    (checked "ibuffer-projectile")
  ];
  "better-defaults" = [
    (checked "mwim")
    (checked "unfill")
  ];
  "typography" = [
    (checked "tildify")
    (checked "typo")
  ];
  "smex" = [
    (checked "smex")
  ];
  "semantic" = [
    (checked "semantic")
    (checked "srefactor")
    (checked "stickyfunc-enhance")
  ];
  "chrome" = [
    (checked "edit-server")
    (checked "gmail-message-mode")
    (checked "flymd")
  ];
  "docker" = [
    (checked "docker")
    (checked "docker-tramp")
    (checked "dockerfile-mode")
  ];
  "deft" = [
    (checked "deft")
  ];
  "vagrant" = [
    (checked "vagrant")
    (checked "vagrant-tramp")
  ];
  "geolocation" = [
    (checked "osx-location")
    (checked "popwin")
    (checked "rase")
    (checked "sunshine")
    (checked "theme-changer")
  ];
  "systemd" = [
    (checked "systemd")
  ];
  "ansible" = [
    (checked "ansible")
    (checked "ansible-doc")
    (checked "company")
    (checked "company-ansible")
    (checked "jinja2-mode")
    (checked "yaml-mode")
  ];
  "fasd" = [
    (checked "fasd")
  ];
  "command-log" = [
    (checked "command-log-mode")
  ];
  "ranger" = [
    (checked "dired")
    (checked "ranger")
  ];
  "nginx" = [
    (checked "nginx-mode")
  ];
  "dash" = [
    (checked "zeal-at-point")
    (checked "helm-dash")
    (checked "counsel-dash")
  ];
  "pandoc" = [
    (checked "pandoc-mode")
    (checked "ox-pandoc")
  ];
  "terraform" = [
    (checked "terraform-mode")
  ];
  "shell" = [
    (checked "comint")
    (checked "company")
    (checked "esh-help")
    (checked "eshell")
    (checked "eshell-prompt-extras")
    (checked "eshell-z")
    (checked "helm")
    (checked "magit")
    (checked "multi-term")
    (checked "org")
    (checked "projectile")
    (checked "shell")
    (checked "shell-pop")
    (checked "term")
    (checked "xterm-color")
    (checked "vi-tilde-fringe")
  ];
  "pdf-tools" = [
    (checked "pdf-tools")
  ];
  "salt" = [
    (checked "salt-mode")
    (checked "smartparens")
  ];
  "ycmd" = [
    (checked "company-ycmd")
    (checked "flycheck-ycmd")
    (checked "eldoc")
    (checked "ycmd")
  ];
  "speed-reading" = [
    (checked "spray")
    (checked "which-key")
  ];
  "puppet" = [
    (checked "company")
    (checked "flycheck")
    (checked "puppet-mode")
  ];
  "rebox" = [
    (checked "rebox2")
  ];
  "prodigy" = [
    (checked "prodigy")
  ];
  "finance" = [
    (checked "company")
    (checked "flycheck-ledger")
    (checked "ledger-mode")
  ];
  "imenu-list" = [
    (checked "golden-ratio")
    (checked "imenu-list")
  ];
  "restclient" = [
    (checked "company")
    (checked "company-restclient")
    (checked "golden-ratio")
    (checked "ob-http")
    (checked "ob-restclient")
    (checked "restclient")
    (checked "restclient-helm")
  ];
  "tmux" = [
    (checked "golden-ratio")
    (checked "tmux")
  ];
  "cfengine" = [
    (checked "cfengine3-mode")
    (checked "company")
    (checked "eldoc")
    (checked "flycheck")
  ];
  "auto-completion" = [
    (checked "auto-complete")
    (checked "ac-ispell")
    (checked "company")
    (checked "company-quickhelp")
    (checked "company-statistics")
    (checked "fuzzy")
    (checked "helm-company")
    (checked "helm-c-yasnippet")
    (checked "hippie-exp")
    (checked "yasnippet")
    (checked "auto-yasnippet")
    (checked "smartparens")
  ];
  "ivy" = [
    (checked "auto-highlight-symbol")
    (checked "bookmark")
    (checked "counsel")
    (checked "counsel-projectile")
    (checked "evil")
    (checked "flx")
    (checked "helm-make")
    (checked "imenu")
    (checked "ivy")
    (checked "ivy-hydra")
    (checked "ivy-spacemacs-help")
    (checked "persp-mode")
    (checked "projectile")
    (checked "smex")
    (checked "swiper")
    (checked "wgrep")
  ];
  "helm" = [
    (checked "ace-jump-helm-line")
    (checked "auto-highlight-symbol")
    (checked "bookmark")
    (checked "helm")
    (checked "helm-ag")
    (checked "helm-descbinds")
    (checked "helm-flx")
    (checked "helm-make")
    (checked "helm-mode-manager")
    (checked "helm-projectile")
    (checked "helm-swoop")
    (checked "helm-themes")
    (checked "helm-spacemacs-help")
    (checked "helm-spacemacs-faq")
    (checked "imenu")
    (checked "persp-mode")
    (checked "popwin")
    (checked "projectile")
  ];
  "keyboard-layout" = [
    (checked "ace-window")
    (checked "avy")
    (checked "comint")
    (checked "company")
    (checked "elfeed")
    (checked "evil")
    (checked "evil-escape")
    (checked "evil-evilified-state")
    (checked "evil-surround")
    (checked "eyebrowse")
    (checked "flycheck")
    (checked "helm")
    (checked "imenu-list")
    (checked "ivy")
    (checked "magit")
    (checked "mu4e")
    (checked "neotree")
    (checked "org")
    (checked "org-agenda")
    (checked "ranger")
    (checked "twittering-mode")
  ];
  "chinese" = [
    (checked "pyim")
    (checked "chinese-wbim")
    (checked "fcitx")
    (checked "find-by-pinyin-dired")
    (checked "ace-pinyin")
    (checked "pangu-spacing")
    (checked "org")
    (checked "youdao-dictionary")
  ];
  "php" = [
    (checked "company")
    (checked "drupal-mode")
    (checked "eldoc")
    (checked "flycheck")
    (checked "ggtags")
    (checked "helm-gtags")
    (checked "php-auto-yasnippets")
    (checked "php-extras")
    (checked "php-mode")
    (checked "phpcbf")
    (checked "phpunit")
  ];
  "asm" = [
    (checked "asm-mode")
    (checked "electric-indent-mode")
    (checked "ggtags")
    (checked "helm-gtags")
    (checked "nasm-mode")
    (checked "x86-lookup")
  ];
  "asciidoc" = [
    (checked "adoc-mode")
  ];
  "autohotkey" = [
    (checked "ahk-mode")
  ];
  "plantuml" = [
    (checked "org")
    (checked "plantuml-mode")
  ];
  "d" = [
    (checked "company")
    (checked "company-dcd")
    (checked "d-mode")
    (checked "flycheck")
    (checked "flycheck-dmd-dub")
    (checked "ggtags")
    (checked "helm-gtags")
  ];
  "idris" = [
    (checked "company")
    (checked "idris-mode")
    (checked "golden-ratio")
    (checked "popwin")
  ];
  "csharp" = [
    (checked "company")
    (checked "csharp-mode")
    (checked "evil-matchit")
    (checked "ggtags")
    (checked "helm-gtags")
    (checked "omnisharp")
  ];
  "elixir" = [
    (checked "alchemist")
    (checked "company")
    (checked "elixir-mode")
    (checked "flycheck")
    (checked "flycheck-mix")
    (checked "flycheck-credo")
    (checked "ggtags")
    (checked "helm-gtags")
    (checked "ob-elixir")
    (checked "popwin")
    (checked "smartparens")
  ];
  "ess" = [
    (checked "ess")
    (checked "ess-R-data-view")
    (checked "ess-smart-equals")
    (checked "golden-ratio")
    (checked "org")
  ];
  "go" = [
    (checked "company")
    (checked "company-go")
    (checked "flycheck")
    (checked "flycheck-gometalinter")
    (checked "ggtags")
    (checked "helm-gtags")
    (checked "go-eldoc")
    (checked "go-mode")
    (checked "go-guru")
    (checked "go-rename")
  ];
  "scala" = [
    (checked "ensime")
    (checked "flycheck")
    (checked "ggtags")
    (checked "helm-gtags")
    (checked "noflet")
    (checked "org")
    (checked "scala-mode")
    (checked "sbt-mode")
  ];
  "windows-scripts" = [
    (checked "dos")
    (checked "ggtags")
    (checked "helm-gtags")
    (checked "powershell")
  ];
  "graphviz" = [
    (checked "graphviz-dot-mode")
    (checked "org")
    (checked "smartparens")
  ];
  "swift" = [
    (checked "flycheck")
    (checked "swift-mode")
  ];
  "javascript" = [
    (checked "coffee-mode")
    (checked "company")
    (checked "company-tern")
    (checked "evil-matchit")
    (checked "flycheck")
    (checked "ggtags")
    (checked "helm-gtags")
    (checked "js-doc")
    (checked "js2-mode")
    (checked "js2-refactor")
    (checked "json-mode")
    (checked "json-snatcher")
    (checked "tern")
    (checked "web-beautify")
    (checked "skewer-mode")
    (checked "livid-mode")
  ];
  "purescript" = [
    (checked "company")
    (checked "flycheck")
    (checked "purescript-mode")
    (checked "psci")
    (checked "psc-ide")
    (checked "popwin")
  ];
  "sml" = [
    (checked "sml-mode")
    (checked "ob-sml")
    (checked "smartparens")
  ];
  "ocaml" = [
    (checked "company")
    (checked "ggtags")
    (checked "helm-gtags")
    (checked "merlin")
    (checked "ocp-indent")
    (checked "smartparens")
    (checked "tuareg")
    (checked "utop")
  ];
  "agda" = [
    (checked "agda")
    (checked "company")
    (checked "golden-ratio")
  ];
  "ruby" = [
    (checked "bundler")
    (checked "chruby")
    (checked "company")
    (checked "enh-ruby-mode")
    (checked "evil-matchit")
    (checked "flycheck")
    (checked "ggtags")
    (checked "helm-gtags")
    (checked "minitest")
    (checked "popwin")
    (checked "rbenv")
    (checked "robe")
    (checked "rspec-mode")
    (checked "rubocop")
    (checked "ruby-mode")
    (checked "ruby-test-mode")
    (checked "ruby-tools")
    (checked "rvm")
    (checked "smartparens")
    (checked "rake")
  ];
  "octave" = [
    (checked "ggtags")
    (checked "helm-gtags")
    (checked "octave")
  ];
  "shaders" = [
    (checked "glsl-mode")
    (checked "company")
    (checked "company-glsl")
  ];
  "rust" = [
    (checked "cargo")
    (checked "company")
    (checked "racer")
    (checked "flycheck")
    (checked "flycheck-rust")
    (checked "ggtags")
    (checked "helm-gtags")
    (checked "rust-mode")
    (checked "toml-mode")
  ];
  "erlang" = [
    (checked "company")
    (checked "erlang")
    (checked "ggtags")
    (checked "helm-gtags")
    (checked "flycheck")
  ];
  "latex" = [
    (checked "auctex")
    (checked "auctex-latexmk")
    (checked "company")
    (checked "company-auctex")
    (checked "evil-matchit")
    (checked "reftex")
    (checked "flycheck")
    (checked "flyspell")
    (checked "ggtags")
    (checked "helm-gtags")
    (checked "smartparens")
    (checked "typo")
    (checked "yasnippet")
    (checked "which-key")
  ];
  "java" = [
    (checked "company")
    (checked "company-emacs-eclim")
    (checked "eclim")
    (checked "ggtags")
    (checked "helm-gtags")
    (checked "java-mode")
  ];
  "typescript" = [
    (checked "company")
    (checked "eldoc")
    (checked "flycheck")
    (checked "tide")
    (checked "typescript-mode")
    (checked "web-mode")
  ];
  "scheme" = [
    (checked "company")
    (checked "geiser")
    (checked "ggtags")
    (checked "helm-gtags")
  ];
  "html" = [
    (checked "company")
    (checked "company-web")
    (checked "css-mode")
    (checked "emmet-mode")
    (checked "evil-matchit")
    (checked "flycheck")
    (checked "haml-mode")
    (checked "helm-css-scss")
    (checked "less-css-mode")
    (checked "pug-mode")
    (checked "sass-mode")
    (checked "scss-mode")
    (checked "slim-mode")
    (checked "smartparens")
    (checked "tagedit")
    (checked "web-mode")
    (checked "yasnippet")
  ];
  "python" = [
    (checked "anaconda-mode")
    (checked "company")
    (checked "company-anaconda")
    (checked "cython-mode")
    (checked "eldoc")
    (checked "evil-matchit")
    (checked "flycheck")
    (checked "ggtags")
    (checked "helm-cscope")
    (checked "helm-gtags")
    (checked "helm-pydoc")
    (checked "hy-mode")
    (checked "live-py-mode")
    (checked "nose")
    (checked "org")
    (checked "pip-requirements")
    (checked "py-isort")
    (checked "pyenv-mode")
    (checked "pylookup")
    (checked "pytest")
    (checked "python")
    (checked "pyvenv")
    (checked "semantic")
    (checked "smartparens")
    (checked "stickyfunc-enhance")
    (checked "xcscope")
    (checked "yapfify")
  ];
  "ipython-notebook" = [
    (checked "ein")
  ];
  "fsharp" = [
    (checked "fsharp-mode")
    (checked "ggtags")
    (checked "helm-gtags")
  ];
  "bibtex" = [
    (checked "auctex")
    (checked "org")
    (checked "org-ref")
    (checked "markdown-mode")
    (checked "helm-bibtex")
    (checked "biblio")
    (checked "biblio-core")
  ];
  "shell-scripts" = [
    (checked "company")
    (checked "company-shell")
    (checked "fish-mode")
    (checked "flycheck")
    (checked "ggtags")
    (checked "helm-gtags")
    (checked "insert-shebang")
    (checked "sh-script")
  ];
  "emacs-lisp" = [
    (checked "auto-compile")
    (checked "company")
    (checked "debug")
    (checked "edebug")
    (checked "eldoc")
    (checked "elisp-slime-nav")
    (checked "emacs-lisp")
    (checked "evil")
    (checked "flycheck")
    (checked "ggtags")
    (checked "helm-gtags")
    (checked "ielm")
    (checked "macrostep")
    (checked "semantic")
    (checked "smartparens")
    (checked "srefactor")
  ];
  "common-lisp" = [
    (checked "auto-highlight-symbol")
    (checked "common-lisp-snippets")
    (checked "ggtags")
    (checked "helm")
    (checked "helm-gtags")
    (checked "slime")
    (checked "slime-company")
  ];
  "racket" = [
    (checked "company")
    (checked "company-quickhelp")
    (checked "ggtags")
    (checked "helm-gtags")
    (checked "racket-mode")
  ];
  "markdown" = [
    (checked "company")
    (checked "company-emoji")
    (checked "emoji-cheat-sheet-plus")
    (checked "gh-md")
    (checked "markdown-mode")
    (checked "markdown-toc")
    (checked "mmm-mode")
    (checked "smartparens")
    (checked "vmd-mode")
  ];
  "haskell" = [
    (checked "cmm-mode")
    (checked "company")
    (checked "company-cabal")
    (checked "company-ghci")
    (checked "company-ghc")
    (checked "flycheck")
    (checked "flycheck-haskell")
    (checked "ggtags")
    (checked "ghc")
    (checked "haskell-mode")
    (checked "haskell-snippets")
    (checked "helm-gtags")
    (checked "helm-hoogle")
    (checked "hindent")
    (checked "hlint-refactor")
    (checked "intero")
  ];
  "c-c++" = [
    (checked "cc-mode")
    (checked "disaster")
    (checked "clang-format")
    (checked "cmake-mode")
    (checked "company")
    (checked "company-c-headers")
    (checked "company-ycmd")
    (checked "flycheck")
    (checked "gdb-mi")
    (checked "ggtags")
    (checked "helm-cscope")
    (checked "helm-gtags")
    (checked "semantic")
    (checked "srefactor")
    (checked "stickyfunc-enhance")
    (checked "ycmd")
    (checked "xcscope")
  ];
  "extra-langs" = [
    (checked "arduino-mode")
    (checked "julia-mode")
    (checked "matlab-mode")
    (checked "qml-mode")
    (checked "scad-mode")
    (checked "stan-mode")
    (checked "thrift")
  ];
  "lua" = [
    (checked "company")
    (checked "flycheck")
    (checked "ggtags")
    (checked "helm-gtags")
    (checked "lua-mode")
  ];
  "csv" = [
    (checked "csv-mode")
  ];
  "faust" = [
    (checked "company")
    (checked "faust-mode")
    (checked "yasnippet")
  ];
  "elm" = [
    (checked "company")
    (checked "elm-mode")
    (checked "flycheck")
    (checked "flycheck-elm")
    (checked "popwin")
    (checked "smartparens")
  ];
  "vimscript" = [
    (checked "vimrc-mode")
    (checked "ggtags")
    (checked "helm-gtags")
    (checked "dactyl-mode")
  ];
  "yaml" = [
    (checked "company")
    (checked "flycheck")
    (checked "yaml-mode")
  ];
  "sql" = [
    (checked "sql")
    (checked "sql-indent")
  ];
  "clojure" = [
    (checked "cider")
    (checked "cider-eval-sexp-fu")
    (checked "clj-refactor")
    (checked "clojure-mode")
    (checked "clojure-snippets")
    (checked "company")
    (checked "eldoc")
    (checked "ggtags")
    (checked "helm-gtags")
    (checked "popwin")
    (checked "smartparens")
    (checked "subword")
    (checked "org")
  ];
  "nim" = [
    (checked "company")
    (checked "flycheck")
    (checked "flycheck-nim")
    (checked "nim-mode")
  ];
  "jabber" = [
    (checked "jabber")
  ];
  "erc" = [
    (checked "company")
    (checked "company-emoji")
    (checked "emoji-cheat-sheet-plus")
    (checked "erc")
    (checked "erc-gitter")
    (checked "erc-hl-nicks")
    (checked "erc-image")
    (checked "erc-sasl")
    (checked "erc-social-graph")
    (checked "erc-tex")
    (checked "erc-view-log")
    (checked "erc-yank")
    (checked "erc-yt")
    (checked "linum")
    (checked "persp-mode")
  ];
  "slack" = [
    (checked "alert")
    (checked "emoji-cheat-sheet-plus")
    (checked "flyspell")
    (checked "linum")
    (checked "persp-mode")
    (checked "slack")
  ];
  "rcirc" = [
    (checked "company")
    (checked "company-emoji")
    (checked "emoji-cheat-sheet-plus")
    (checked "flyspell")
    (checked "helm-rcirc")
    (checked "persp-mode")
    (checked "rcirc")
    (checked "rcirc-color")
    (checked "rcirc-notify")
  ];
  "mu4e" = [
    (checked "mu4e")
    (checked "mu4e-alert")
    (checked "mu4e-maildirs-extension")
    (checked "org")
  ];
  "gnus" = [
    (checked "gnus")
  ];
  "syntax-checking" = [
    (checked "flycheck")
    (checked "flycheck-pos-tip")
    (checked "popwin")
  ];
  "spell-checking" = [
    (checked "auto-dictionary")
    (checked "flyspell")
    (checked "flyspell-correct")
    (checked "flyspell-correct-ivy")
    (checked "flyspell-correct-helm")
    (checked "flyspell-correct-popup")
    (checked "flyspell-popup")
  ];
}
