#!/usr/bin/env nix-shell
#! nix-shell -i "emacs --batch -l $HOME/.emacs.d/core/core-load-paths.el -l" -p emacs26-nox

(defconst spacemacs-version "0.200.13")
(require 'core-spacemacs)
(spacemacs/init)

(princ "# Generated by dotspacemacs-used-themes.el\n")
(princ "ps:\n")
(princ "[\n")
(dolist (theme dotspacemacs-themes)
  (let ((ps (spacemacs//get-theme-package theme)))
    (when ps
      (princ (concat "  ps." (prin1-to-string (symbol-name ps)) "\n")))))
(princ "]\n")
