#!/usr/bin/env nix-shell
#! nix-shell -i "emacs --batch -l $HOME/.emacs.d/core/core-load-paths.el -l" -p emacs26-nox

(defconst spacemacs-version "0.200.13")
(require 'core-spacemacs)
(spacemacs/init)
(configuration-layer/sync 'no-install)

(princ "# Generated by dotspacemacs-used-layers.el\n")
(princ "ls:\n")
(princ "[\n")
(dolist (layer-symbol configuration-layer--used-layers)
  (princ (concat "  ls." (prin1-to-string (symbol-name layer-symbol)) "\n")))
(princ "]\n")
