#!/usr/bin/env nix-shell
#! nix-shell -i "emacs --batch -l $HOME/.emacs.d/core/core-load-paths.el -l" -p emacs26-nox

(require 'core-configuration-layer)
(configuration-layer/discover-layers)
(configuration-layer/make-all-packages nil)
(princ "# Generated by spacemacs2nix.el\n")
(princ "p:\n")
(princ "let checked = n:\n")
(princ "  let p' = p.${n} or null;\n")
(princ "  in if p'.meta.broken or false then null else p';\n")
(princ "in\n")
(princ "[\n")
(dolist (package (configuration-layer/get-packages-list))
  (princ (concat "  (checked " (prin1-to-string (symbol-name package)) ")\n")))
(princ "]\n")
