esphome:
  name: bedroom
  platform: ESP8266
  board: esp01

wifi:
  ssid: !secret home_ssid
  password: !secret home_password

sensor:
  - platform: dht
    pin: 2
    model: DHT11
    temperature:
      name: "Bedroom Temperature"
    humidity:
      name: "Bedroom Humidity"
    update_interval: 60s

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

web_server:
  port: 80
