esphome:
  name: garage
  platform: ESP8266
  board: esp01_1m

script:
  - id: toggle_relay
    then:
      - uart.write: [0xA0, 0x01, 0x01, 0xA2]
      - delay: 100ms
      - uart.write: [0xA0, 0x01, 0x00, 0xA1]

wifi:
  reboot_timeout: "1min"

  manual_ip:
    static_ip: 192.168.1.14
    gateway: 192.168.1.1
    subnet: 255.255.255.0

  ssid: !secret garage_ssid
  password: !secret garage_password

logger:
  baud_rate: 0

api:

ota:

uart:
  baud_rate: 115200
  tx_pin: GPIO1
  rx_pin: GPIO3

cover:
  - platform: template
    name: Garage Door
    device_class: garage
    optimistic: true
    assumed_state: true
    open_action:
      - script.execute: toggle_relay
    close_action:
      - script.execute: toggle_relay
    stop_action:
      - script.execute: toggle_relay

web_server:
  port: 80
